FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod ./
RUN go mod download || true
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o auth ./cmd/services/auth

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/auth .
EXPOSE 50051
CMD ["./auth"]
