FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod ./
RUN go mod download || true
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o chat ./cmd/services/chat

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/chat .
EXPOSE 50054
CMD ["./chat"]
