// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/workout/v1/workout.proto

package workoutv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCoursesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesRequest) Reset() {
	*x = GetCoursesRequest{}
	mi := &file_proto_workout_v1_workout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesRequest) ProtoMessage() {}

func (x *GetCoursesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workout_v1_workout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesRequest.ProtoReflect.Descriptor instead.
func (*GetCoursesRequest) Descriptor() ([]byte, []int) {
	return file_proto_workout_v1_workout_proto_rawDescGZIP(), []int{0}
}

type Course struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Course) Reset() {
	*x = Course{}
	mi := &file_proto_workout_v1_workout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workout_v1_workout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_proto_workout_v1_workout_proto_rawDescGZIP(), []int{1}
}

func (x *Course) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Course) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Course) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Course) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetCoursesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courses       []*Course              `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesResponse) Reset() {
	*x = GetCoursesResponse{}
	mi := &file_proto_workout_v1_workout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesResponse) ProtoMessage() {}

func (x *GetCoursesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workout_v1_workout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesResponse.ProtoReflect.Descriptor instead.
func (*GetCoursesResponse) Descriptor() ([]byte, []int) {
	return file_proto_workout_v1_workout_proto_rawDescGZIP(), []int{2}
}

func (x *GetCoursesResponse) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

type GetEnrolledCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnrolledCourseRequest) Reset() {
	*x = GetEnrolledCourseRequest{}
	mi := &file_proto_workout_v1_workout_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnrolledCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnrolledCourseRequest) ProtoMessage() {}

func (x *GetEnrolledCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workout_v1_workout_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnrolledCourseRequest.ProtoReflect.Descriptor instead.
func (*GetEnrolledCourseRequest) Descriptor() ([]byte, []int) {
	return file_proto_workout_v1_workout_proto_rawDescGZIP(), []int{3}
}

func (x *GetEnrolledCourseRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetEnrolledCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	IsEnrolled    bool                   `protobuf:"varint,5,opt,name=is_enrolled,json=isEnrolled,proto3" json:"is_enrolled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnrolledCourseResponse) Reset() {
	*x = GetEnrolledCourseResponse{}
	mi := &file_proto_workout_v1_workout_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnrolledCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnrolledCourseResponse) ProtoMessage() {}

func (x *GetEnrolledCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workout_v1_workout_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnrolledCourseResponse.ProtoReflect.Descriptor instead.
func (*GetEnrolledCourseResponse) Descriptor() ([]byte, []int) {
	return file_proto_workout_v1_workout_proto_rawDescGZIP(), []int{4}
}

func (x *GetEnrolledCourseResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetEnrolledCourseResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetEnrolledCourseResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetEnrolledCourseResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *GetEnrolledCourseResponse) GetIsEnrolled() bool {
	if x != nil {
		return x.IsEnrolled
	}
	return false
}

type GetTodayWorkoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodayWorkoutRequest) Reset() {
	*x = GetTodayWorkoutRequest{}
	mi := &file_proto_workout_v1_workout_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodayWorkoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodayWorkoutRequest) ProtoMessage() {}

func (x *GetTodayWorkoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workout_v1_workout_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodayWorkoutRequest.ProtoReflect.Descriptor instead.
func (*GetTodayWorkoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_workout_v1_workout_proto_rawDescGZIP(), []int{5}
}

func (x *GetTodayWorkoutRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Exercise struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sets          int32                  `protobuf:"varint,2,opt,name=sets,proto3" json:"sets,omitempty"`
	Reps          string                 `protobuf:"bytes,3,opt,name=reps,proto3" json:"reps,omitempty"`
	Weight        string                 `protobuf:"bytes,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Instructions  string                 `protobuf:"bytes,5,opt,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exercise) Reset() {
	*x = Exercise{}
	mi := &file_proto_workout_v1_workout_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exercise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exercise) ProtoMessage() {}

func (x *Exercise) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workout_v1_workout_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exercise.ProtoReflect.Descriptor instead.
func (*Exercise) Descriptor() ([]byte, []int) {
	return file_proto_workout_v1_workout_proto_rawDescGZIP(), []int{6}
}

func (x *Exercise) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Exercise) GetSets() int32 {
	if x != nil {
		return x.Sets
	}
	return 0
}

func (x *Exercise) GetReps() string {
	if x != nil {
		return x.Reps
	}
	return ""
}

func (x *Exercise) GetWeight() string {
	if x != nil {
		return x.Weight
	}
	return ""
}

func (x *Exercise) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

type GetTodayWorkoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	DayNumber     int32                  `protobuf:"varint,3,opt,name=day_number,json=dayNumber,proto3" json:"day_number,omitempty"`
	IsRestDay     bool                   `protobuf:"varint,4,opt,name=is_rest_day,json=isRestDay,proto3" json:"is_rest_day,omitempty"`
	Exercises     []*Exercise            `protobuf:"bytes,5,rep,name=exercises,proto3" json:"exercises,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodayWorkoutResponse) Reset() {
	*x = GetTodayWorkoutResponse{}
	mi := &file_proto_workout_v1_workout_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodayWorkoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodayWorkoutResponse) ProtoMessage() {}

func (x *GetTodayWorkoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workout_v1_workout_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodayWorkoutResponse.ProtoReflect.Descriptor instead.
func (*GetTodayWorkoutResponse) Descriptor() ([]byte, []int) {
	return file_proto_workout_v1_workout_proto_rawDescGZIP(), []int{7}
}

func (x *GetTodayWorkoutResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTodayWorkoutResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetTodayWorkoutResponse) GetDayNumber() int32 {
	if x != nil {
		return x.DayNumber
	}
	return 0
}

func (x *GetTodayWorkoutResponse) GetIsRestDay() bool {
	if x != nil {
		return x.IsRestDay
	}
	return false
}

func (x *GetTodayWorkoutResponse) GetExercises() []*Exercise {
	if x != nil {
		return x.Exercises
	}
	return nil
}

type GetWorkoutHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkoutHistoryRequest) Reset() {
	*x = GetWorkoutHistoryRequest{}
	mi := &file_proto_workout_v1_workout_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkoutHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkoutHistoryRequest) ProtoMessage() {}

func (x *GetWorkoutHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workout_v1_workout_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkoutHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetWorkoutHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_workout_v1_workout_proto_rawDescGZIP(), []int{8}
}

func (x *GetWorkoutHistoryRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type WorkoutLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkoutTitle  string                 `protobuf:"bytes,2,opt,name=workout_title,json=workoutTitle,proto3" json:"workout_title,omitempty"`
	CompletedAt   string                 `protobuf:"bytes,3,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkoutLog) Reset() {
	*x = WorkoutLog{}
	mi := &file_proto_workout_v1_workout_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkoutLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutLog) ProtoMessage() {}

func (x *WorkoutLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workout_v1_workout_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutLog.ProtoReflect.Descriptor instead.
func (*WorkoutLog) Descriptor() ([]byte, []int) {
	return file_proto_workout_v1_workout_proto_rawDescGZIP(), []int{9}
}

func (x *WorkoutLog) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WorkoutLog) GetWorkoutTitle() string {
	if x != nil {
		return x.WorkoutTitle
	}
	return ""
}

func (x *WorkoutLog) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

type GetWorkoutHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*WorkoutLog          `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkoutHistoryResponse) Reset() {
	*x = GetWorkoutHistoryResponse{}
	mi := &file_proto_workout_v1_workout_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkoutHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkoutHistoryResponse) ProtoMessage() {}

func (x *GetWorkoutHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workout_v1_workout_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkoutHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetWorkoutHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_workout_v1_workout_proto_rawDescGZIP(), []int{10}
}

func (x *GetWorkoutHistoryResponse) GetLogs() []*WorkoutLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

type EnrollRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId           uint32                 `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	OnboardingDataJson string                 `protobuf:"bytes,3,opt,name=onboarding_data_json,json=onboardingDataJson,proto3" json:"onboarding_data_json,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_proto_workout_v1_workout_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workout_v1_workout_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_proto_workout_v1_workout_proto_rawDescGZIP(), []int{11}
}

func (x *EnrollRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EnrollRequest) GetCourseId() uint32 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *EnrollRequest) GetOnboardingDataJson() string {
	if x != nil {
		return x.OnboardingDataJson
	}
	return ""
}

type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_proto_workout_v1_workout_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workout_v1_workout_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_proto_workout_v1_workout_proto_rawDescGZIP(), []int{12}
}

func (x *EnrollResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnrollResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CancelEnrollmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelEnrollmentRequest) Reset() {
	*x = CancelEnrollmentRequest{}
	mi := &file_proto_workout_v1_workout_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelEnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelEnrollmentRequest) ProtoMessage() {}

func (x *CancelEnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workout_v1_workout_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelEnrollmentRequest.ProtoReflect.Descriptor instead.
func (*CancelEnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_workout_v1_workout_proto_rawDescGZIP(), []int{13}
}

func (x *CancelEnrollmentRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CancelEnrollmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelEnrollmentResponse) Reset() {
	*x = CancelEnrollmentResponse{}
	mi := &file_proto_workout_v1_workout_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelEnrollmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelEnrollmentResponse) ProtoMessage() {}

func (x *CancelEnrollmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workout_v1_workout_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelEnrollmentResponse.ProtoReflect.Descriptor instead.
func (*CancelEnrollmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_workout_v1_workout_proto_rawDescGZIP(), []int{14}
}

func (x *CancelEnrollmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CompleteWorkoutDayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DayId         uint32                 `protobuf:"varint,2,opt,name=day_id,json=dayId,proto3" json:"day_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteWorkoutDayRequest) Reset() {
	*x = CompleteWorkoutDayRequest{}
	mi := &file_proto_workout_v1_workout_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteWorkoutDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteWorkoutDayRequest) ProtoMessage() {}

func (x *CompleteWorkoutDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workout_v1_workout_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteWorkoutDayRequest.ProtoReflect.Descriptor instead.
func (*CompleteWorkoutDayRequest) Descriptor() ([]byte, []int) {
	return file_proto_workout_v1_workout_proto_rawDescGZIP(), []int{15}
}

func (x *CompleteWorkoutDayRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CompleteWorkoutDayRequest) GetDayId() uint32 {
	if x != nil {
		return x.DayId
	}
	return 0
}

type CompleteWorkoutDayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteWorkoutDayResponse) Reset() {
	*x = CompleteWorkoutDayResponse{}
	mi := &file_proto_workout_v1_workout_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteWorkoutDayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteWorkoutDayResponse) ProtoMessage() {}

func (x *CompleteWorkoutDayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workout_v1_workout_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteWorkoutDayResponse.ProtoReflect.Descriptor instead.
func (*CompleteWorkoutDayResponse) Descriptor() ([]byte, []int) {
	return file_proto_workout_v1_workout_proto_rawDescGZIP(), []int{16}
}

func (x *CompleteWorkoutDayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_workout_v1_workout_proto protoreflect.FileDescriptor

const file_proto_workout_v1_workout_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/workout/v1/workout.proto\x12\n" +
	"workout.v1\"\x13\n" +
	"\x11GetCoursesRequest\"b\n" +
	"\x06Course\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\"B\n" +
	"\x12GetCoursesResponse\x12,\n" +
	"\acourses\x18\x01 \x03(\v2\x12.workout.v1.CourseR\acourses\"3\n" +
	"\x18GetEnrolledCourseRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"\x96\x01\n" +
	"\x19GetEnrolledCourseResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x1f\n" +
	"\vis_enrolled\x18\x05 \x01(\bR\n" +
	"isEnrolled\"1\n" +
	"\x16GetTodayWorkoutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"\x82\x01\n" +
	"\bExercise\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04sets\x18\x02 \x01(\x05R\x04sets\x12\x12\n" +
	"\x04reps\x18\x03 \x01(\tR\x04reps\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\tR\x06weight\x12\"\n" +
	"\finstructions\x18\x05 \x01(\tR\finstructions\"\xb2\x01\n" +
	"\x17GetTodayWorkoutResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"day_number\x18\x03 \x01(\x05R\tdayNumber\x12\x1e\n" +
	"\vis_rest_day\x18\x04 \x01(\bR\tisRestDay\x122\n" +
	"\texercises\x18\x05 \x03(\v2\x14.workout.v1.ExerciseR\texercises\"3\n" +
	"\x18GetWorkoutHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"d\n" +
	"\n" +
	"WorkoutLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12#\n" +
	"\rworkout_title\x18\x02 \x01(\tR\fworkoutTitle\x12!\n" +
	"\fcompleted_at\x18\x03 \x01(\tR\vcompletedAt\"G\n" +
	"\x19GetWorkoutHistoryResponse\x12*\n" +
	"\x04logs\x18\x01 \x03(\v2\x16.workout.v1.WorkoutLogR\x04logs\"w\n" +
	"\rEnrollRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\rR\bcourseId\x120\n" +
	"\x14onboarding_data_json\x18\x03 \x01(\tR\x12onboardingDataJson\"D\n" +
	"\x0eEnrollResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"2\n" +
	"\x17CancelEnrollmentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"4\n" +
	"\x18CancelEnrollmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"K\n" +
	"\x19CompleteWorkoutDayRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x15\n" +
	"\x06day_id\x18\x02 \x01(\rR\x05dayId\"6\n" +
	"\x1aCompleteWorkoutDayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x82\x05\n" +
	"\x0eWorkoutService\x12K\n" +
	"\n" +
	"GetCourses\x12\x1d.workout.v1.GetCoursesRequest\x1a\x1e.workout.v1.GetCoursesResponse\x12`\n" +
	"\x11GetEnrolledCourse\x12$.workout.v1.GetEnrolledCourseRequest\x1a%.workout.v1.GetEnrolledCourseResponse\x12Z\n" +
	"\x0fGetTodayWorkout\x12\".workout.v1.GetTodayWorkoutRequest\x1a#.workout.v1.GetTodayWorkoutResponse\x12`\n" +
	"\x11GetWorkoutHistory\x12$.workout.v1.GetWorkoutHistoryRequest\x1a%.workout.v1.GetWorkoutHistoryResponse\x12?\n" +
	"\x06Enroll\x12\x19.workout.v1.EnrollRequest\x1a\x1a.workout.v1.EnrollResponse\x12]\n" +
	"\x10CancelEnrollment\x12#.workout.v1.CancelEnrollmentRequest\x1a$.workout.v1.CancelEnrollmentResponse\x12c\n" +
	"\x12CompleteWorkoutDay\x12%.workout.v1.CompleteWorkoutDayRequest\x1a&.workout.v1.CompleteWorkoutDayResponseBIZGgithub.com/akhilbabu26/jinnx-fitweb/backend2/proto/workout/v1;workoutv1b\x06proto3"

var (
	file_proto_workout_v1_workout_proto_rawDescOnce sync.Once
	file_proto_workout_v1_workout_proto_rawDescData []byte
)

func file_proto_workout_v1_workout_proto_rawDescGZIP() []byte {
	file_proto_workout_v1_workout_proto_rawDescOnce.Do(func() {
		file_proto_workout_v1_workout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_workout_v1_workout_proto_rawDesc), len(file_proto_workout_v1_workout_proto_rawDesc)))
	})
	return file_proto_workout_v1_workout_proto_rawDescData
}

var file_proto_workout_v1_workout_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_workout_v1_workout_proto_goTypes = []any{
	(*GetCoursesRequest)(nil),          // 0: workout.v1.GetCoursesRequest
	(*Course)(nil),                     // 1: workout.v1.Course
	(*GetCoursesResponse)(nil),         // 2: workout.v1.GetCoursesResponse
	(*GetEnrolledCourseRequest)(nil),   // 3: workout.v1.GetEnrolledCourseRequest
	(*GetEnrolledCourseResponse)(nil),  // 4: workout.v1.GetEnrolledCourseResponse
	(*GetTodayWorkoutRequest)(nil),     // 5: workout.v1.GetTodayWorkoutRequest
	(*Exercise)(nil),                   // 6: workout.v1.Exercise
	(*GetTodayWorkoutResponse)(nil),    // 7: workout.v1.GetTodayWorkoutResponse
	(*GetWorkoutHistoryRequest)(nil),   // 8: workout.v1.GetWorkoutHistoryRequest
	(*WorkoutLog)(nil),                 // 9: workout.v1.WorkoutLog
	(*GetWorkoutHistoryResponse)(nil),  // 10: workout.v1.GetWorkoutHistoryResponse
	(*EnrollRequest)(nil),              // 11: workout.v1.EnrollRequest
	(*EnrollResponse)(nil),             // 12: workout.v1.EnrollResponse
	(*CancelEnrollmentRequest)(nil),    // 13: workout.v1.CancelEnrollmentRequest
	(*CancelEnrollmentResponse)(nil),   // 14: workout.v1.CancelEnrollmentResponse
	(*CompleteWorkoutDayRequest)(nil),  // 15: workout.v1.CompleteWorkoutDayRequest
	(*CompleteWorkoutDayResponse)(nil), // 16: workout.v1.CompleteWorkoutDayResponse
}
var file_proto_workout_v1_workout_proto_depIdxs = []int32{
	1,  // 0: workout.v1.GetCoursesResponse.courses:type_name -> workout.v1.Course
	6,  // 1: workout.v1.GetTodayWorkoutResponse.exercises:type_name -> workout.v1.Exercise
	9,  // 2: workout.v1.GetWorkoutHistoryResponse.logs:type_name -> workout.v1.WorkoutLog
	0,  // 3: workout.v1.WorkoutService.GetCourses:input_type -> workout.v1.GetCoursesRequest
	3,  // 4: workout.v1.WorkoutService.GetEnrolledCourse:input_type -> workout.v1.GetEnrolledCourseRequest
	5,  // 5: workout.v1.WorkoutService.GetTodayWorkout:input_type -> workout.v1.GetTodayWorkoutRequest
	8,  // 6: workout.v1.WorkoutService.GetWorkoutHistory:input_type -> workout.v1.GetWorkoutHistoryRequest
	11, // 7: workout.v1.WorkoutService.Enroll:input_type -> workout.v1.EnrollRequest
	13, // 8: workout.v1.WorkoutService.CancelEnrollment:input_type -> workout.v1.CancelEnrollmentRequest
	15, // 9: workout.v1.WorkoutService.CompleteWorkoutDay:input_type -> workout.v1.CompleteWorkoutDayRequest
	2,  // 10: workout.v1.WorkoutService.GetCourses:output_type -> workout.v1.GetCoursesResponse
	4,  // 11: workout.v1.WorkoutService.GetEnrolledCourse:output_type -> workout.v1.GetEnrolledCourseResponse
	7,  // 12: workout.v1.WorkoutService.GetTodayWorkout:output_type -> workout.v1.GetTodayWorkoutResponse
	10, // 13: workout.v1.WorkoutService.GetWorkoutHistory:output_type -> workout.v1.GetWorkoutHistoryResponse
	12, // 14: workout.v1.WorkoutService.Enroll:output_type -> workout.v1.EnrollResponse
	14, // 15: workout.v1.WorkoutService.CancelEnrollment:output_type -> workout.v1.CancelEnrollmentResponse
	16, // 16: workout.v1.WorkoutService.CompleteWorkoutDay:output_type -> workout.v1.CompleteWorkoutDayResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_workout_v1_workout_proto_init() }
func file_proto_workout_v1_workout_proto_init() {
	if File_proto_workout_v1_workout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_workout_v1_workout_proto_rawDesc), len(file_proto_workout_v1_workout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_workout_v1_workout_proto_goTypes,
		DependencyIndexes: file_proto_workout_v1_workout_proto_depIdxs,
		MessageInfos:      file_proto_workout_v1_workout_proto_msgTypes,
	}.Build()
	File_proto_workout_v1_workout_proto = out.File
	file_proto_workout_v1_workout_proto_goTypes = nil
	file_proto_workout_v1_workout_proto_depIdxs = nil
}
