// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/workout/v1/workout.proto

package workoutv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkoutService_GetCourses_FullMethodName         = "/workout.v1.WorkoutService/GetCourses"
	WorkoutService_GetEnrolledCourse_FullMethodName  = "/workout.v1.WorkoutService/GetEnrolledCourse"
	WorkoutService_GetTodayWorkout_FullMethodName    = "/workout.v1.WorkoutService/GetTodayWorkout"
	WorkoutService_GetWorkoutHistory_FullMethodName  = "/workout.v1.WorkoutService/GetWorkoutHistory"
	WorkoutService_Enroll_FullMethodName             = "/workout.v1.WorkoutService/Enroll"
	WorkoutService_CancelEnrollment_FullMethodName   = "/workout.v1.WorkoutService/CancelEnrollment"
	WorkoutService_CompleteWorkoutDay_FullMethodName = "/workout.v1.WorkoutService/CompleteWorkoutDay"
)

// WorkoutServiceClient is the client API for WorkoutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkoutServiceClient interface {
	GetCourses(ctx context.Context, in *GetCoursesRequest, opts ...grpc.CallOption) (*GetCoursesResponse, error)
	GetEnrolledCourse(ctx context.Context, in *GetEnrolledCourseRequest, opts ...grpc.CallOption) (*GetEnrolledCourseResponse, error)
	GetTodayWorkout(ctx context.Context, in *GetTodayWorkoutRequest, opts ...grpc.CallOption) (*GetTodayWorkoutResponse, error)
	GetWorkoutHistory(ctx context.Context, in *GetWorkoutHistoryRequest, opts ...grpc.CallOption) (*GetWorkoutHistoryResponse, error)
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
	CancelEnrollment(ctx context.Context, in *CancelEnrollmentRequest, opts ...grpc.CallOption) (*CancelEnrollmentResponse, error)
	CompleteWorkoutDay(ctx context.Context, in *CompleteWorkoutDayRequest, opts ...grpc.CallOption) (*CompleteWorkoutDayResponse, error)
}

type workoutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkoutServiceClient(cc grpc.ClientConnInterface) WorkoutServiceClient {
	return &workoutServiceClient{cc}
}

func (c *workoutServiceClient) GetCourses(ctx context.Context, in *GetCoursesRequest, opts ...grpc.CallOption) (*GetCoursesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCoursesResponse)
	err := c.cc.Invoke(ctx, WorkoutService_GetCourses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) GetEnrolledCourse(ctx context.Context, in *GetEnrolledCourseRequest, opts ...grpc.CallOption) (*GetEnrolledCourseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEnrolledCourseResponse)
	err := c.cc.Invoke(ctx, WorkoutService_GetEnrolledCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) GetTodayWorkout(ctx context.Context, in *GetTodayWorkoutRequest, opts ...grpc.CallOption) (*GetTodayWorkoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTodayWorkoutResponse)
	err := c.cc.Invoke(ctx, WorkoutService_GetTodayWorkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) GetWorkoutHistory(ctx context.Context, in *GetWorkoutHistoryRequest, opts ...grpc.CallOption) (*GetWorkoutHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkoutHistoryResponse)
	err := c.cc.Invoke(ctx, WorkoutService_GetWorkoutHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, WorkoutService_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) CancelEnrollment(ctx context.Context, in *CancelEnrollmentRequest, opts ...grpc.CallOption) (*CancelEnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelEnrollmentResponse)
	err := c.cc.Invoke(ctx, WorkoutService_CancelEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) CompleteWorkoutDay(ctx context.Context, in *CompleteWorkoutDayRequest, opts ...grpc.CallOption) (*CompleteWorkoutDayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteWorkoutDayResponse)
	err := c.cc.Invoke(ctx, WorkoutService_CompleteWorkoutDay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkoutServiceServer is the server API for WorkoutService service.
// All implementations must embed UnimplementedWorkoutServiceServer
// for forward compatibility.
type WorkoutServiceServer interface {
	GetCourses(context.Context, *GetCoursesRequest) (*GetCoursesResponse, error)
	GetEnrolledCourse(context.Context, *GetEnrolledCourseRequest) (*GetEnrolledCourseResponse, error)
	GetTodayWorkout(context.Context, *GetTodayWorkoutRequest) (*GetTodayWorkoutResponse, error)
	GetWorkoutHistory(context.Context, *GetWorkoutHistoryRequest) (*GetWorkoutHistoryResponse, error)
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	CancelEnrollment(context.Context, *CancelEnrollmentRequest) (*CancelEnrollmentResponse, error)
	CompleteWorkoutDay(context.Context, *CompleteWorkoutDayRequest) (*CompleteWorkoutDayResponse, error)
	mustEmbedUnimplementedWorkoutServiceServer()
}

// UnimplementedWorkoutServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkoutServiceServer struct{}

func (UnimplementedWorkoutServiceServer) GetCourses(context.Context, *GetCoursesRequest) (*GetCoursesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCourses not implemented")
}
func (UnimplementedWorkoutServiceServer) GetEnrolledCourse(context.Context, *GetEnrolledCourseRequest) (*GetEnrolledCourseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEnrolledCourse not implemented")
}
func (UnimplementedWorkoutServiceServer) GetTodayWorkout(context.Context, *GetTodayWorkoutRequest) (*GetTodayWorkoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTodayWorkout not implemented")
}
func (UnimplementedWorkoutServiceServer) GetWorkoutHistory(context.Context, *GetWorkoutHistoryRequest) (*GetWorkoutHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkoutHistory not implemented")
}
func (UnimplementedWorkoutServiceServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedWorkoutServiceServer) CancelEnrollment(context.Context, *CancelEnrollmentRequest) (*CancelEnrollmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelEnrollment not implemented")
}
func (UnimplementedWorkoutServiceServer) CompleteWorkoutDay(context.Context, *CompleteWorkoutDayRequest) (*CompleteWorkoutDayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteWorkoutDay not implemented")
}
func (UnimplementedWorkoutServiceServer) mustEmbedUnimplementedWorkoutServiceServer() {}
func (UnimplementedWorkoutServiceServer) testEmbeddedByValue()                        {}

// UnsafeWorkoutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkoutServiceServer will
// result in compilation errors.
type UnsafeWorkoutServiceServer interface {
	mustEmbedUnimplementedWorkoutServiceServer()
}

func RegisterWorkoutServiceServer(s grpc.ServiceRegistrar, srv WorkoutServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkoutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkoutService_ServiceDesc, srv)
}

func _WorkoutService_GetCourses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCoursesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).GetCourses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_GetCourses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).GetCourses(ctx, req.(*GetCoursesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_GetEnrolledCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnrolledCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).GetEnrolledCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_GetEnrolledCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).GetEnrolledCourse(ctx, req.(*GetEnrolledCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_GetTodayWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTodayWorkoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).GetTodayWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_GetTodayWorkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).GetTodayWorkout(ctx, req.(*GetTodayWorkoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_GetWorkoutHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkoutHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).GetWorkoutHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_GetWorkoutHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).GetWorkoutHistory(ctx, req.(*GetWorkoutHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_CancelEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).CancelEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_CancelEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).CancelEnrollment(ctx, req.(*CancelEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_CompleteWorkoutDay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteWorkoutDayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).CompleteWorkoutDay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_CompleteWorkoutDay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).CompleteWorkoutDay(ctx, req.(*CompleteWorkoutDayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkoutService_ServiceDesc is the grpc.ServiceDesc for WorkoutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkoutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workout.v1.WorkoutService",
	HandlerType: (*WorkoutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCourses",
			Handler:    _WorkoutService_GetCourses_Handler,
		},
		{
			MethodName: "GetEnrolledCourse",
			Handler:    _WorkoutService_GetEnrolledCourse_Handler,
		},
		{
			MethodName: "GetTodayWorkout",
			Handler:    _WorkoutService_GetTodayWorkout_Handler,
		},
		{
			MethodName: "GetWorkoutHistory",
			Handler:    _WorkoutService_GetWorkoutHistory_Handler,
		},
		{
			MethodName: "Enroll",
			Handler:    _WorkoutService_Enroll_Handler,
		},
		{
			MethodName: "CancelEnrollment",
			Handler:    _WorkoutService_CancelEnrollment_Handler,
		},
		{
			MethodName: "CompleteWorkoutDay",
			Handler:    _WorkoutService_CompleteWorkoutDay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/workout/v1/workout.proto",
}
