// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/subscription/v1/subscription.proto

package subv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionRequest) Reset() {
	*x = GetSubscriptionRequest{}
	mi := &file_proto_subscription_v1_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionRequest) ProtoMessage() {}

func (x *GetSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_v1_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *GetSubscriptionRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetSubscriptionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CurrentPeriodEnd *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=current_period_end,json=currentPeriodEnd,proto3" json:"current_period_end,omitempty"`
	RazorpaySubId    string                 `protobuf:"bytes,3,opt,name=razorpay_sub_id,json=razorpaySubId,proto3" json:"razorpay_sub_id,omitempty"`
	IsActive         bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSubscriptionResponse) Reset() {
	*x = GetSubscriptionResponse{}
	mi := &file_proto_subscription_v1_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionResponse) ProtoMessage() {}

func (x *GetSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_v1_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *GetSubscriptionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetSubscriptionResponse) GetCurrentPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.CurrentPeriodEnd
	}
	return nil
}

func (x *GetSubscriptionResponse) GetRazorpaySubId() string {
	if x != nil {
		return x.RazorpaySubId
	}
	return ""
}

func (x *GetSubscriptionResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CreateRazorpaySubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRazorpaySubscriptionRequest) Reset() {
	*x = CreateRazorpaySubscriptionRequest{}
	mi := &file_proto_subscription_v1_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRazorpaySubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRazorpaySubscriptionRequest) ProtoMessage() {}

func (x *CreateRazorpaySubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_v1_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRazorpaySubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateRazorpaySubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRazorpaySubscriptionRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateRazorpaySubscriptionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	KeyId          string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateRazorpaySubscriptionResponse) Reset() {
	*x = CreateRazorpaySubscriptionResponse{}
	mi := &file_proto_subscription_v1_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRazorpaySubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRazorpaySubscriptionResponse) ProtoMessage() {}

func (x *CreateRazorpaySubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_v1_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRazorpaySubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CreateRazorpaySubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRazorpaySubscriptionResponse) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *CreateRazorpaySubscriptionResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type HandleWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleWebhookRequest) Reset() {
	*x = HandleWebhookRequest{}
	mi := &file_proto_subscription_v1_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleWebhookRequest) ProtoMessage() {}

func (x *HandleWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_v1_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleWebhookRequest.ProtoReflect.Descriptor instead.
func (*HandleWebhookRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *HandleWebhookRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *HandleWebhookRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type HandleWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleWebhookResponse) Reset() {
	*x = HandleWebhookResponse{}
	mi := &file_proto_subscription_v1_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleWebhookResponse) ProtoMessage() {}

func (x *HandleWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_v1_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleWebhookResponse.ProtoReflect.Descriptor instead.
func (*HandleWebhookResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscription_v1_subscription_proto_rawDescGZIP(), []int{5}
}

func (x *HandleWebhookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_subscription_v1_subscription_proto protoreflect.FileDescriptor

const file_proto_subscription_v1_subscription_proto_rawDesc = "" +
	"\n" +
	"(proto/subscription/v1/subscription.proto\x12\x0fsubscription.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"1\n" +
	"\x16GetSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"\xc0\x01\n" +
	"\x17GetSubscriptionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12H\n" +
	"\x12current_period_end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x10currentPeriodEnd\x12&\n" +
	"\x0frazorpay_sub_id\x18\x03 \x01(\tR\rrazorpaySubId\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"<\n" +
	"!CreateRazorpaySubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"d\n" +
	"\"CreateRazorpaySubscriptionResponse\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\"N\n" +
	"\x14HandleWebhookRequest\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"1\n" +
	"\x15HandleWebhookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe3\x02\n" +
	"\x13SubscriptionService\x12d\n" +
	"\x0fGetSubscription\x12'.subscription.v1.GetSubscriptionRequest\x1a(.subscription.v1.GetSubscriptionResponse\x12\x85\x01\n" +
	"\x1aCreateRazorpaySubscription\x122.subscription.v1.CreateRazorpaySubscriptionRequest\x1a3.subscription.v1.CreateRazorpaySubscriptionResponse\x12^\n" +
	"\rHandleWebhook\x12%.subscription.v1.HandleWebhookRequest\x1a&.subscription.v1.HandleWebhookResponseBJZHgithub.com/akhilbabu26/jinnx-fitweb/backend2/proto/subscription/v1;subv1b\x06proto3"

var (
	file_proto_subscription_v1_subscription_proto_rawDescOnce sync.Once
	file_proto_subscription_v1_subscription_proto_rawDescData []byte
)

func file_proto_subscription_v1_subscription_proto_rawDescGZIP() []byte {
	file_proto_subscription_v1_subscription_proto_rawDescOnce.Do(func() {
		file_proto_subscription_v1_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_subscription_v1_subscription_proto_rawDesc), len(file_proto_subscription_v1_subscription_proto_rawDesc)))
	})
	return file_proto_subscription_v1_subscription_proto_rawDescData
}

var file_proto_subscription_v1_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_subscription_v1_subscription_proto_goTypes = []any{
	(*GetSubscriptionRequest)(nil),             // 0: subscription.v1.GetSubscriptionRequest
	(*GetSubscriptionResponse)(nil),            // 1: subscription.v1.GetSubscriptionResponse
	(*CreateRazorpaySubscriptionRequest)(nil),  // 2: subscription.v1.CreateRazorpaySubscriptionRequest
	(*CreateRazorpaySubscriptionResponse)(nil), // 3: subscription.v1.CreateRazorpaySubscriptionResponse
	(*HandleWebhookRequest)(nil),               // 4: subscription.v1.HandleWebhookRequest
	(*HandleWebhookResponse)(nil),              // 5: subscription.v1.HandleWebhookResponse
	(*timestamppb.Timestamp)(nil),              // 6: google.protobuf.Timestamp
}
var file_proto_subscription_v1_subscription_proto_depIdxs = []int32{
	6, // 0: subscription.v1.GetSubscriptionResponse.current_period_end:type_name -> google.protobuf.Timestamp
	0, // 1: subscription.v1.SubscriptionService.GetSubscription:input_type -> subscription.v1.GetSubscriptionRequest
	2, // 2: subscription.v1.SubscriptionService.CreateRazorpaySubscription:input_type -> subscription.v1.CreateRazorpaySubscriptionRequest
	4, // 3: subscription.v1.SubscriptionService.HandleWebhook:input_type -> subscription.v1.HandleWebhookRequest
	1, // 4: subscription.v1.SubscriptionService.GetSubscription:output_type -> subscription.v1.GetSubscriptionResponse
	3, // 5: subscription.v1.SubscriptionService.CreateRazorpaySubscription:output_type -> subscription.v1.CreateRazorpaySubscriptionResponse
	5, // 6: subscription.v1.SubscriptionService.HandleWebhook:output_type -> subscription.v1.HandleWebhookResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_subscription_v1_subscription_proto_init() }
func file_proto_subscription_v1_subscription_proto_init() {
	if File_proto_subscription_v1_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_subscription_v1_subscription_proto_rawDesc), len(file_proto_subscription_v1_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_subscription_v1_subscription_proto_goTypes,
		DependencyIndexes: file_proto_subscription_v1_subscription_proto_depIdxs,
		MessageInfos:      file_proto_subscription_v1_subscription_proto_msgTypes,
	}.Build()
	File_proto_subscription_v1_subscription_proto = out.File
	file_proto_subscription_v1_subscription_proto_goTypes = nil
	file_proto_subscription_v1_subscription_proto_depIdxs = nil
}
