// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/video/v1/video.proto

package videov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomName      string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionTokenRequest) Reset() {
	*x = CreateSessionTokenRequest{}
	mi := &file_proto_video_v1_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionTokenRequest) ProtoMessage() {}

func (x *CreateSessionTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_v1_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_v1_video_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionTokenRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateSessionTokenRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

type CreateSessionTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	LivekitUrl    string                 `protobuf:"bytes,2,opt,name=livekit_url,json=livekitUrl,proto3" json:"livekit_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionTokenResponse) Reset() {
	*x = CreateSessionTokenResponse{}
	mi := &file_proto_video_v1_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionTokenResponse) ProtoMessage() {}

func (x *CreateSessionTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_v1_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_v1_video_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateSessionTokenResponse) GetLivekitUrl() string {
	if x != nil {
		return x.LivekitUrl
	}
	return ""
}

type GetSessionListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionListRequest) Reset() {
	*x = GetSessionListRequest{}
	mi := &file_proto_video_v1_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionListRequest) ProtoMessage() {}

func (x *GetSessionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_v1_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionListRequest.ProtoReflect.Descriptor instead.
func (*GetSessionListRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_v1_video_proto_rawDescGZIP(), []int{2}
}

func (x *GetSessionListRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type VideoSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomName      string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	ScheduledAt   string                 `protobuf:"bytes,4,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoSession) Reset() {
	*x = VideoSession{}
	mi := &file_proto_video_v1_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoSession) ProtoMessage() {}

func (x *VideoSession) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_v1_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoSession.ProtoReflect.Descriptor instead.
func (*VideoSession) Descriptor() ([]byte, []int) {
	return file_proto_video_v1_video_proto_rawDescGZIP(), []int{3}
}

func (x *VideoSession) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VideoSession) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *VideoSession) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoSession) GetScheduledAt() string {
	if x != nil {
		return x.ScheduledAt
	}
	return ""
}

type GetSessionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*VideoSession        `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionListResponse) Reset() {
	*x = GetSessionListResponse{}
	mi := &file_proto_video_v1_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionListResponse) ProtoMessage() {}

func (x *GetSessionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_v1_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionListResponse.ProtoReflect.Descriptor instead.
func (*GetSessionListResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_v1_video_proto_rawDescGZIP(), []int{4}
}

func (x *GetSessionListResponse) GetSessions() []*VideoSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

var File_proto_video_v1_video_proto protoreflect.FileDescriptor

const file_proto_video_v1_video_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/video/v1/video.proto\x12\bvideo.v1\"Q\n" +
	"\x19CreateSessionTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\"S\n" +
	"\x1aCreateSessionTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1f\n" +
	"\vlivekit_url\x18\x02 \x01(\tR\n" +
	"livekitUrl\"0\n" +
	"\x15GetSessionListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"t\n" +
	"\fVideoSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12!\n" +
	"\fscheduled_at\x18\x04 \x01(\tR\vscheduledAt\"L\n" +
	"\x16GetSessionListResponse\x122\n" +
	"\bsessions\x18\x01 \x03(\v2\x16.video.v1.VideoSessionR\bsessions2\xc4\x01\n" +
	"\fVideoService\x12_\n" +
	"\x12CreateSessionToken\x12#.video.v1.CreateSessionTokenRequest\x1a$.video.v1.CreateSessionTokenResponse\x12S\n" +
	"\x0eGetSessionList\x12\x1f.video.v1.GetSessionListRequest\x1a .video.v1.GetSessionListResponseBEZCgithub.com/akhilbabu26/jinnx-fitweb/backend2/proto/video/v1;videov1b\x06proto3"

var (
	file_proto_video_v1_video_proto_rawDescOnce sync.Once
	file_proto_video_v1_video_proto_rawDescData []byte
)

func file_proto_video_v1_video_proto_rawDescGZIP() []byte {
	file_proto_video_v1_video_proto_rawDescOnce.Do(func() {
		file_proto_video_v1_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_video_v1_video_proto_rawDesc), len(file_proto_video_v1_video_proto_rawDesc)))
	})
	return file_proto_video_v1_video_proto_rawDescData
}

var file_proto_video_v1_video_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_video_v1_video_proto_goTypes = []any{
	(*CreateSessionTokenRequest)(nil),  // 0: video.v1.CreateSessionTokenRequest
	(*CreateSessionTokenResponse)(nil), // 1: video.v1.CreateSessionTokenResponse
	(*GetSessionListRequest)(nil),      // 2: video.v1.GetSessionListRequest
	(*VideoSession)(nil),               // 3: video.v1.VideoSession
	(*GetSessionListResponse)(nil),     // 4: video.v1.GetSessionListResponse
}
var file_proto_video_v1_video_proto_depIdxs = []int32{
	3, // 0: video.v1.GetSessionListResponse.sessions:type_name -> video.v1.VideoSession
	0, // 1: video.v1.VideoService.CreateSessionToken:input_type -> video.v1.CreateSessionTokenRequest
	2, // 2: video.v1.VideoService.GetSessionList:input_type -> video.v1.GetSessionListRequest
	1, // 3: video.v1.VideoService.CreateSessionToken:output_type -> video.v1.CreateSessionTokenResponse
	4, // 4: video.v1.VideoService.GetSessionList:output_type -> video.v1.GetSessionListResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_video_v1_video_proto_init() }
func file_proto_video_v1_video_proto_init() {
	if File_proto_video_v1_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_video_v1_video_proto_rawDesc), len(file_proto_video_v1_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_video_v1_video_proto_goTypes,
		DependencyIndexes: file_proto_video_v1_video_proto_depIdxs,
		MessageInfos:      file_proto_video_v1_video_proto_msgTypes,
	}.Build()
	File_proto_video_v1_video_proto = out.File
	file_proto_video_v1_video_proto_goTypes = nil
	file_proto_video_v1_video_proto_depIdxs = nil
}
